package token

import (
	"testing"
)

func Test_stringToTokenReceiverPayload(t *testing.T) {
	str := `{"access_token":"eyJhbGciOiJSUzI1NiIsInR5cCIgOiAiSldUIiwia2lkIiA6ICJyOFNsUW9qT2RGbGVOLUstdHQ0ODhOWEFoNEZ5Sm5TZDVOMWlFVWN1WTJFIn0.eyJleHAiOjE3MzI5MDQzMDUsImlhdCI6MTczMjkwNDI4MiwianRpIjoiOThmMzU0YjMtYzQ1Ny00OWJhLTljMmQtMmYyZTQwZWRmMmJjIiwiaXNzIjoiaHR0cDovL2xvY2FsaG9zdDo4MDgwL3JlYWxtcy90ZXN0LXJlYWxtIiwiYXVkIjoiYWNjb3VudCIsInN1YiI6Ijg3NDNmZDA2LTBkMTgtNDA5ZC04YmM2LTgyNzM0MzkwOTc4MCIsInR5cCI6IkJlYXJlciIsImF6cCI6InRlc3QtY2xpZW50IiwiYWNyIjoiMSIsInJlYWxtX2FjY2VzcyI6eyJyb2xlcyI6WyJkZWZhdWx0LXJvbGVzLXRlc3QtcmVhbG0iLCJvZmZsaW5lX2FjY2VzcyIsInVtYV9hdXRob3JpemF0aW9uIl19LCJyZXNvdXJjZV9hY2Nlc3MiOnsiYWNjb3VudCI6eyJyb2xlcyI6WyJtYW5hZ2UtYWNjb3VudCIsIm1hbmFnZS1hY2NvdW50LWxpbmtzIiwidmlldy1wcm9maWxlIl19fSwic2NvcGUiOiJwcm9maWxlIGVtYWlsIiwiZW1haWxfdmVyaWZpZWQiOmZhbHNlLCJjbGllbnRIb3N0IjoiMTcyLjIyLjAuMSIsInByZWZlcnJlZF91c2VybmFtZSI6InNlcnZpY2UtYWNjb3VudC10ZXN0LWNsaWVudCIsImNsaWVudEFkZHJlc3MiOiIxNzIuMjIuMC4xIiwiY2xpZW50X2lkIjoidGVzdC1jbGllbnQifQ.bx0oi4dGEXyEniZX4kNsw4npKAWhHLrYS69UcnzfxtHUVMM_IVpN3ObxpMJfKcBbu3vDXLDByYkCBK0pCZUG9HGSkk1ahZ8H5XWvvlLroQzuPZYGAYxn9mzoG_A2RbdRJCSlFXQGCIYiO-OGA--fFGEORxZn-lEeLeljTRveMBpUAHEE8fvZfiNADKyJK6wX6ZtkUioqO-zrQd4q6-WkKeV2rQzNPx-WYBdFHaBNBr9kSMtQYPXGlcLn7KNAkTxzl_G5qoWZWcOW29-iTS5S_zn2auoVsC58cNlGk7-bafpJTe_T_3RuZiZPfxjYT8M_ygV2k5eDEqRDA3AgmoZ1PQ","expires_in":23,"refresh_expires_in":0,"token_type":"Bearer","not-before-policy":0,"scope":"profile email"}`

	payload, err := stringToTokenReceiverPayload([]byte(str))
	if err != nil {
		t.Errorf("Error while convert token str: %v", err)
		return
	}

	if payload.Error.IsSet() {
		t.Errorf("Error in payload is set: %v", payload)
		return
	}

	if payload.ExpirationSeconds != 23 {
		t.Errorf("Wrong number of expiration seconds: expected=23, got=%d", payload.ExpirationSeconds)
		return
	}

	if payload.TokenStr != "eyJhbGciOiJSUzI1NiIsInR5cCIgOiAiSldUIiwia2lkIiA6ICJyOFNsUW9qT2RGbGVOLUstdHQ0ODhOWEFoNEZ5Sm5TZDVOMWlFVWN1WTJFIn0.eyJleHAiOjE3MzI5MDQzMDUsImlhdCI6MTczMjkwNDI4MiwianRpIjoiOThmMzU0YjMtYzQ1Ny00OWJhLTljMmQtMmYyZTQwZWRmMmJjIiwiaXNzIjoiaHR0cDovL2xvY2FsaG9zdDo4MDgwL3JlYWxtcy90ZXN0LXJlYWxtIiwiYXVkIjoiYWNjb3VudCIsInN1YiI6Ijg3NDNmZDA2LTBkMTgtNDA5ZC04YmM2LTgyNzM0MzkwOTc4MCIsInR5cCI6IkJlYXJlciIsImF6cCI6InRlc3QtY2xpZW50IiwiYWNyIjoiMSIsInJlYWxtX2FjY2VzcyI6eyJyb2xlcyI6WyJkZWZhdWx0LXJvbGVzLXRlc3QtcmVhbG0iLCJvZmZsaW5lX2FjY2VzcyIsInVtYV9hdXRob3JpemF0aW9uIl19LCJyZXNvdXJjZV9hY2Nlc3MiOnsiYWNjb3VudCI6eyJyb2xlcyI6WyJtYW5hZ2UtYWNjb3VudCIsIm1hbmFnZS1hY2NvdW50LWxpbmtzIiwidmlldy1wcm9maWxlIl19fSwic2NvcGUiOiJwcm9maWxlIGVtYWlsIiwiZW1haWxfdmVyaWZpZWQiOmZhbHNlLCJjbGllbnRIb3N0IjoiMTcyLjIyLjAuMSIsInByZWZlcnJlZF91c2VybmFtZSI6InNlcnZpY2UtYWNjb3VudC10ZXN0LWNsaWVudCIsImNsaWVudEFkZHJlc3MiOiIxNzIuMjIuMC4xIiwiY2xpZW50X2lkIjoidGVzdC1jbGllbnQifQ.bx0oi4dGEXyEniZX4kNsw4npKAWhHLrYS69UcnzfxtHUVMM_IVpN3ObxpMJfKcBbu3vDXLDByYkCBK0pCZUG9HGSkk1ahZ8H5XWvvlLroQzuPZYGAYxn9mzoG_A2RbdRJCSlFXQGCIYiO-OGA--fFGEORxZn-lEeLeljTRveMBpUAHEE8fvZfiNADKyJK6wX6ZtkUioqO-zrQd4q6-WkKeV2rQzNPx-WYBdFHaBNBr9kSMtQYPXGlcLn7KNAkTxzl_G5qoWZWcOW29-iTS5S_zn2auoVsC58cNlGk7-bafpJTe_T_3RuZiZPfxjYT8M_ygV2k5eDEqRDA3AgmoZ1PQ" {
		t.Errorf("Wrong token string, got=%s", payload.TokenStr)
		return
	}
}
